# Generated by Django 3.0.6 on 2020-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='futured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
