# Generated by Django 3.0.6 on 2020-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produc', '0002_products_futured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
